/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(my_amplifier.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(099f5fba7e163d73e8f3245c004fe233)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/unina/my_amplifier.h>
// pydoc.h is automatically generated in the build directory
#include <my_amplifier_pydoc.h>

void bind_my_amplifier(py::module& m)
{

    using my_amplifier    = gr::unina::my_amplifier;


    py::class_<my_amplifier, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<my_amplifier>>(m, "my_amplifier", D(my_amplifier))

        .def(py::init(&my_amplifier::make),
           D(my_amplifier,make)
        )
        



        ;




}








