/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rms_voltmeter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(da6a98787a39e8071cc3469024dd42ca)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/unina/rms_voltmeter.h>
// pydoc.h is automatically generated in the build directory
#include <rms_voltmeter_pydoc.h>

void bind_rms_voltmeter(py::module& m)
{

    using rms_voltmeter    = gr::unina::rms_voltmeter;


    py::class_<rms_voltmeter, gr::sync_decimator,
        std::shared_ptr<rms_voltmeter>>(m, "rms_voltmeter", D(rms_voltmeter))

        .def(py::init(&rms_voltmeter::make),
           D(rms_voltmeter,make)
        )
        



        ;




}








